'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MineProducts.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comma separated values (*.csv)|*.csv.
        '''</summary>
        Friend ReadOnly Property CsvSaveDialogFilter() As String
            Get
                Return ResourceManager.GetString("CsvSaveDialogFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property ErrorDialogTitleCreatingProduct() As String
            Get
                Return ResourceManager.GetString("ErrorDialogTitleCreatingProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.3048.
        '''</summary>
        Friend ReadOnly Property FeetSecToMtsSec() As String
            Get
                Return ResourceManager.GetString("FeetSecToMtsSec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 25.4.
        '''</summary>
        Friend ReadOnly Property InchesToMillimeters() As String
            Get
                Return ResourceManager.GetString("InchesToMillimeters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incomplete fields. Please check all required fields are complete..
        '''</summary>
        Friend ReadOnly Property IncompleteFieldsErrorCreatingProduct() As String
            Get
                Return ResourceManager.GetString("IncompleteFieldsErrorCreatingProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid fields. Please check number fields don&apos;t contain letters..
        '''</summary>
        Friend ReadOnly Property InvalidFieldsErrorCreatingProduct() As String
            Get
                Return ResourceManager.GetString("InvalidFieldsErrorCreatingProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create.
        '''</summary>
        Friend ReadOnly Property NewProductButtonText() As String
            Get
                Return ResourceManager.GetString("NewProductButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Mine.
        '''</summary>
        Friend ReadOnly Property SaveMineBtnText() As String
            Get
                Return ResourceManager.GetString("SaveMineBtnText", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
